export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const INDIAN_LANGUAGES: LanguageOption[] = [
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🚩' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
];

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  mr: {
    appTitle: 'किल्ले महाराष्ट्र 3D',
    appSubtitle: 'महाराष्ट्रातील ४० ऐतिहासिक किल्ले',
    searchPlaceholder: 'किल्ला, जिल्हा किंवा इतिहास शोधा...',
    keyBtn: 'मॅप की',
    wikiSectionTitle: 'विकिपीडिया अधिकृत इतिहास',
    aiSectionTitle: 'सामरिक माहिती व इतिहास',
    ytSectionTitle: 'टॉप ५ युट्यूब माहितीपट व ४के टूर',
    readWikiBtn: 'संपूर्ण विकिपीडिया पहा',
    rulerLabel: 'राज्यकर्ते / घराणे',
    battleLabel: 'प्रमुख युद्धे व घटना',
    archLabel: 'वास्तू रचना वैशिष्ट्ये',
    terrainFlyto: '३डी प्रदेश फ्लायटू',
    networkLoading: '४० किल्ल्यांचे नेटवर्क लोड होत आहे...',
    district: 'जिल्हा',
  },
  hi: {
    appTitle: 'महाराष्ट्र दुर्ग 3D',
    appSubtitle: 'महाराष्ट्र के ४० ऐतिहासिक किले',
    searchPlaceholder: 'किले, जिले या इतिहास खोजें...',
    keyBtn: 'मैप कुंजी',
    wikiSectionTitle: 'विकिपीडिया आधिकारिक इतिहास',
    aiSectionTitle: 'रणनीतिक जानकारी व इतिहास',
    ytSectionTitle: 'टॉप ५ यूट्यूब डॉक्यूमेंट्री व 4K टूर',
    readWikiBtn: 'पूरा विकिपीडिया पढ़ें',
    rulerLabel: 'शासक / राजवंश',
    battleLabel: 'प्रमुख युद्ध व घटनाएं',
    archLabel: 'स्थापत्य कला विशेषताएं',
    terrainFlyto: '3D भूभाग फ्लाईटू',
    networkLoading: '40 किलों का नेटवर्क लोड हो रहा है...',
    district: 'जिला',
  },
  en: {
    appTitle: 'Forts of Maharashtra 3D',
    appSubtitle: '40 Historic Forts of Maharashtra',
    searchPlaceholder: 'Search forts, districts, history...',
    keyBtn: 'Map Key',
    wikiSectionTitle: 'WIKIPEDIA OFFICIAL HISTORY',
    aiSectionTitle: 'STRATEGIC INSIGHTS & HISTORY',
    ytSectionTitle: 'Top 5 YouTube Documentaries & Tours',
    readWikiBtn: 'Read Wikipedia Article',
    rulerLabel: 'Ruler / Dynasty',
    battleLabel: 'Key Battles & Events',
    archLabel: 'Architectural Highlights',
    terrainFlyto: '3D Terrain Flyto',
    networkLoading: 'Loading 40 Forts Network...',
    district: 'District',
  },
  gu: {
    appTitle: 'મહારાષ્ટ્ર કિલ્લા 3D',
    appSubtitle: 'મહારાષ્ટ્રના ૪૦ ઐતિહાસિક કિલ્લા',
    searchPlaceholder: 'કિલ્લા, જિલ્લાઓ શોધો...',
    keyBtn: 'મેપ કી',
    wikiSectionTitle: 'વિકિપીડિયા અધિકૃત ઇતિહાસ',
    aiSectionTitle: 'વ્યૂહાત્મક માહિતી',
    ytSectionTitle: 'ટોપ ૫ યુટ્યુબ ડોક્યુમેન્ટ્રી',
    readWikiBtn: 'વિકિપીડિયા વાંચો',
    rulerLabel: 'શાસક / વંશ',
    battleLabel: 'મુખ્ય યુદ્ધો',
    archLabel: 'સ્થાપત્ય વિશેષતાઓ',
    terrainFlyto: '3D ફ્લાયટૂ',
    networkLoading: 'કિલ્લા નેટવર્ક લોડ થઈ રહ્યું છે...',
    district: 'જિલ્લો',
  },
  ta: {
    appTitle: 'மகாராஷ்டிரா கோட்டைகள் 3D',
    appSubtitle: '40 வரலாற்று கோட்டைகள்',
    searchPlaceholder: 'கோட்டைகள், மாவட்டங்களை தேடுக...',
    keyBtn: 'மேப் கீ',
    wikiSectionTitle: 'விக்கிப்பீடியா வரலாறு',
    aiSectionTitle: 'மூலோபாய தகவல்கள்',
    ytSectionTitle: 'டாப் 5 யூடியூப் வீடியோக்கள்',
    readWikiBtn: 'விக்கிப்பீடியா படிக்க',
    rulerLabel: 'ஆட்சியாளர் / வம்சம்',
    battleLabel: 'முக்கிய போர்கள்',
    archLabel: 'கட்டிடக்கலை',
    terrainFlyto: '3D பறக்கும் பார்வை',
    networkLoading: 'கோட்டைகள் ஏற்றப்படுகிறது...',
    district: 'மாவட்டம்',
  },
  te: {
    appTitle: 'మహారాష్ట్ర కోటలు 3D',
    appSubtitle: '40 చారిత్రక కోటలు',
    searchPlaceholder: 'కోటలు, జిల్లాలను శోధించండి...',
    keyBtn: 'మ్యాప్ కీ',
    wikiSectionTitle: 'వికీపీడియా చరిత్ర',
    aiSectionTitle: 'వ్యూహాత్మక సమాచారం',
    ytSectionTitle: 'టాప్ 5 యూట్యూబ్ వీడియోలు',
    readWikiBtn: 'వికీపీడియా చదవండి',
    rulerLabel: 'పాలకుడు / వంశం',
    battleLabel: 'ప్రధాన యుద్ధాలు',
    archLabel: 'శిల్పకళ',
    terrainFlyto: '3D ఫ్లైటూ',
    networkLoading: 'కోటల నెట్‌వర్క్ లోడ్ అవుతోంది...',
    district: 'జిల్లా',
  },
  kn: {
    appTitle: 'ಮಹಾರಾಷ್ಟ್ರ ಕೋಟೆಗಳು 3D',
    appSubtitle: '೪೦ ಐತಿಹಾಸಿಕ ಕೋಟೆಗಳು',
    searchPlaceholder: 'ಕೋಟೆಗಳು, ಜಿಲ್ಲೆಗಳನ್ನು ಹುಡುಕಿ...',
    keyBtn: 'ಮ್ಯಾಪ್ ಕೀ',
    wikiSectionTitle: 'ವಿಕಿಪೀಡಿಯಾ ಇತಿಹಾಸ',
    aiSectionTitle: 'ಕಾರ್ಯತಂತ್ರದ ಮಾಹಿತಿ',
    ytSectionTitle: 'ಟಾಪ್ ೫ ಯೂಟ್ಯೂಬ್ ವೀಡಿಯೊಗಳು',
    readWikiBtn: 'ವಿಕಿಪೀಡಿಯಾ ಓದಿ',
    rulerLabel: 'ಆಳಿದವರು / ರಾಜವಂಶ',
    battleLabel: 'ಪ್ರಮುಖ ಯುದ್ಧಗಳು',
    archLabel: 'ವಾಸ್ತುಶಿಲ್ಪ',
    terrainFlyto: '3D ಫ್ಲೈಟೂ',
    networkLoading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    district: 'ಜಿಲ್ಲೆ',
  },
  bn: {
    appTitle: 'মহারাষ্ট্র দুর্গ 3D',
    appSubtitle: '৪০টি ঐতিহাসিক দুর্গ',
    searchPlaceholder: 'দুর্গ বা জেলা খুঁজুন...',
    keyBtn: 'ম্যাপ কি',
    wikiSectionTitle: 'উইকিপিডিয়া ইতিহাস',
    aiSectionTitle: 'কৌশলগত বিবরণ',
    ytSectionTitle: 'সেরা ৫ ইউটিউব ভিডিও',
    readWikiBtn: 'উইকিপিডিয়া পড়ুন',
    rulerLabel: 'শাসক / রাজবংশ',
    battleLabel: 'প্রধান যুদ্ধ',
    archLabel: 'স্থাপত্য বৈশিষ্ট্য',
    terrainFlyto: '3D ফ্লাইটু',
    networkLoading: 'দুর্গ নেটওয়ার্ক লোড হচ্ছে...',
    district: 'জেলা',
  },
  ml: {
    appTitle: 'മഹാരാഷ്ട്ര കോട്ടകൾ 3D',
    appSubtitle: '40 ചരിത്രപരമായ കോട്ടകൾ',
    searchPlaceholder: 'കോട്ടകൾ തിരയുക...',
    keyBtn: 'മാപ്പ് കീ',
    wikiSectionTitle: 'വിക്കിപീഡിയ ചരിത്രം',
    aiSectionTitle: 'തന്ത്രപരമായ വിവരങ്ങൾ',
    ytSectionTitle: 'ടോപ് 5 യൂട്യൂബ് വീഡിയോകൾ',
    readWikiBtn: 'വിക്കിപീഡിയ വായിക്കുക',
    rulerLabel: 'ഭരണാധികാരി / രാജവംശം',
    battleLabel: 'പ്രധാന യുദ്ധങ്ങൾ',
    archLabel: 'വാസ്തുവിദ്യ',
    terrainFlyto: '3D ഫ്ലൈറ്റൂ',
    networkLoading: 'ലോഡ് ചെയ്യുന്നു...',
    district: 'ജില്ല',
  },
};

export interface FortTranslation {
  name: string;
  district: string;
  type: string;
  desc: string;
  landmark: string;
}

export const FORT_TRANSLATIONS: Record<string, Record<string, FortTranslation>> = {
  mr: {
    'Raigad Fort': { name: 'रायगड किल्ला', district: 'रायगड जिल्हा', type: 'गिरीदुर्ग', desc: 'मराठा साम्राज्याची राजधानी, छत्रपती शिवाजी महाराजांचा राज्याभिषेक सोहळा पार पडलेले स्थान.', landmark: 'महादरवाजा व हिरकणी बुरुज' },
    'Shivneri Fort': { name: 'शिवनेरी किल्ला', district: 'पुणे जिल्हा', type: 'गिरीदुर्ग', desc: 'छत्रपती शिवाजी महाराजांचे जन्मस्थान (१९ फेब्रुवारी १६३०), सात सुरक्षा दरवाजे.', landmark: 'शिवाई देवी मंदिर व बादामी तलाव' },
    'Sinhagad Fort': { name: 'सिंहगड किल्ला', district: 'पुणे जिल्हा', type: 'गिरीदुर्ग', desc: 'पूर्वीचा कोंढाणा, तानाजी मालुसरे यांच्या पराक्रमाचे अमर प्रतीक.', landmark: 'कल्याण दरवाजा व तानाजी स्मारक' },
    'Rajgad Fort': { name: 'राजगड किल्ला', district: 'पुणे जिल्हा', type: 'गिरीदुर्ग', desc: 'मराठा साम्राज्याची सलग २६ वर्षे पहिली मुख्य राजधानी, संजीवनी व सुवेळा माची.', landmark: 'पद्मावती माची व बालेकिल्ला' },
    'Torna Fort': { name: 'तोरणा किल्ला', district: 'पुणे जिल्हा', type: 'गिरीदुर्ग', desc: 'शिवरायांनी वयाच्या १६ व्या वर्षी जिंकलेला पहिला किल्ला (प्रचंडगड).', landmark: 'झुंझार माची व मेंगाई मंदिर' },
    'Pratapgad Fort': { name: 'प्रतापगड किल्ला', district: 'सातारा जिल्हा', type: 'गिरीदुर्ग', desc: 'अफझलखानाचा पराभव झालेली ऐतिहासिक रणभूमी (१६५९).', landmark: 'भवानी मंदिर व छत्रपती शिवराय पुतळा' },
    'Murud-Janjira Fort': { name: 'मुरुड-जंजिरा किल्ला', district: 'रायगड जिल्हा', type: 'जलदुर्ग', desc: 'अरबी समुद्रातील अजिंक्य जलदुर्ग, गोड्या पाण्याची दोन तळी.', landmark: 'कलाल बांगडी तोफ व तटबंदी' },
    'Sindhudurg Fort': { name: 'सिंधुदुर्ग किल्ला', district: 'सिंधुदुर्ग जिल्हा', type: 'जलदुर्ग', desc: 'मराठा आरमाराचे मुख्य केंद्र, शिवरायांच्या हाताचे व पायाचे ठसे.', landmark: 'रणबाईपाट दरवाजा व शिवराजेश्वर मंदिर' },
    'Vijaydurg Fort': { name: 'विजयदुर्ग किल्ला', district: 'सिंधुदुर्ग जिल्हा', type: 'जलदुर्ग', desc: 'कान्होजी आंग्रे यांच्या आरमाराचा बालेकिल्ला, पाण्याखालील दगडी भिंत.', landmark: 'त्रिस्तरीय तटबंदी व बुरुज' },
    'Daulatabad Fort (Devgiri)': { name: 'दौलताबाद किल्ला (देवगिरी)', district: 'छत्रपती संभाजीनगर', type: 'गिरीदुर्ग', desc: '२०० मीटर उंच त्रिकोणी टेकडीवर बांधलेला अजिंक्य मध्ययुगीन किल्ला, भूलभुलैया.', landmark: 'चांद मिनार व भूलभुलैया' },
    'Panhala Fort': { name: 'पन्हाळा किल्ला', district: 'कोल्हापूर जिल्हा', type: 'गिरीदुर्ग', desc: 'बाजीप्रभू देशपांडे यांच्या पावनखिंडीतील बलिदानाशी जोडलेला किल्ला.', landmark: 'अंबरखाना व चार दरवाजा' },
    'Lohagad Fort': { name: 'लोहगड किल्ला', district: 'पुणे जिल्हा', type: 'गिरीदुर्ग', desc: 'लोणावळ्याजवळील प्रसिद्ध किल्ला, विंचूकाटा माची.', landmark: 'विंचूकाटा माची व गणेश दरवाजा' },
  },
  hi: {
    'Raigad Fort': { name: 'रायगढ़ किला', district: 'रायगढ़ जिला', type: 'गिरि दुर्ग', desc: 'मराठा साम्राज्य की राजधानी, छत्रपति शिवाजी महाराज का राज्याभिषेक स्थल।', landmark: 'महा दरवाजा व हिरकणी बुर्ज' },
    'Shivneri Fort': { name: 'शिवनेरी किला', district: 'पुणे जिला', type: 'गिरि दुर्ग', desc: 'छत्रपति शिवाजी महाराज का जन्मस्थान (1630), सात सुरक्षा द्वार।', landmark: 'शिवाई देवी मंदिर व बादामी तालाब' },
    'Sinhagad Fort': { name: 'सिंहगढ़ किला', district: 'पुणे जिला', type: 'गिरि दुर्ग', desc: 'पूर्व नाम कोंढाणा, तानाजी मालुसरे के पराक्रम का ऐतिहासिक प्रतीक।', landmark: 'कल्याण दरवाजा व तानाजी स्मारक' },
    'Rajgad Fort': { name: 'राजगढ़ किला', district: 'पुणे जिला', type: 'गिरि दुर्ग', desc: 'मराठा साम्राज्य की 26 वर्षों तक प्रथम राजधानी।', landmark: 'पद्मावती माची व बालेकिला' },
    'Torna Fort': { name: 'तोरणा किला', district: 'पुणे जिला', type: 'गिरि दुर्ग', desc: 'शिवाजी महाराज द्वारा 16 वर्ष की आयु में जीता गया पहला किला।', landmark: 'झुंझार माची व मेंगाई मंदिर' },
    'Pratapgad Fort': { name: 'प्रतापगढ़ किला', district: 'सतारा जिला', type: 'गिरि दुर्ग', desc: 'अफ़ज़ल ख़ान के वध का ऐतिहासिक स्थल (1659)।', landmark: 'भवानी मंदिर व शिवजी की प्रतिमा' },
    'Murud-Janjira Fort': { name: 'मुरुड-जंजीरा किला', district: 'रायगढ़ जिला', type: 'जल दुर्ग', desc: 'अरब सागर का अजेय समुद्री किला।', landmark: 'कलाल बांगड़ी तोप व मीठे पानी की झीलें' },
    'Sindhudurg Fort': { name: 'सिंधुदुर्ग किला', district: 'सिंधुदुर्ग जिला', type: 'जल दुर्ग', desc: 'मराठा नौसेना का मुख्य केंद्र, शिवाजी महाराज के पदचिह्न।', landmark: 'शिवराजेश्वर मंदिर व बुर्ज' },
  },
};
